quarkus:

  mailer:
    from: register@dreambond.com.na
    host: mail.dreambond.com.na
    port: 587
    username: register@dreambond.com.na
    password: Register@2025$
    auth-methods: LOGIN
    login: REQUIRED
    mock: true

  http:
    port: 8080
  swagger-ui:
    always-include: true
    path: /swagger-ui.html
  smallrye-openapi:
    path: /swagger

  flyway:
    migrate-at-start: true

app:
  email:
    verification:
      subject: Verification Code
      text: Your verification code is %s

"%test":
  quarkus:
    flyway:
        enabled: false
    datasources:
      devservices:
        enabled: true

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: postgres
      password: postgres
      jdbc:
        url: jdbc:postgresql://host.docker.internal:5412/sneaker-db
        max-size: 16

"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      username: postgres
      password: postgres
      jdbc:
        url: jdbc:postgresql://host.docker.internal:5412/sneaker-db
        max-size: 16
